In [16]:
myList=[]
for i in range(2000,3201):
    if (i % 7 == 0) & (i%5 != 0):
        myList=myList+[i]
print(myList)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [17]:
def Factorial(n):
    a=1
    for i in range(n,1,-1):
        a=a*i
    return a
Factorial(7)


5040

In [18]:
def Dictionary(n):
    dict= {}
    for i in range(1,n+1):
        dict[i]=i*i
    return dict
Dictionary(8)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [23]:
s=input("please enter your string ")
l=len(s)
n=input("please enter a number between 0 and "+str(l-1))
while (int(n)>len(s)-1):
    n=input("please enter a valid number ")
first_part = s[:int(n)] 
last_part = s[int(n)+1:]
print(first_part + last_part)
 
    


please enter your string hello
please enter a number between 0 and 42
helo


In [25]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
lis=arr.tolist()
print(lis)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [9]:
import numpy as np
def cov(arr1, arr2):
    print(np.cov(arr1,arr2))
    
cov([1,2,3],[3,4,5])
    

[[1. 1.]
 [1. 1.]]


In [10]:
import math
c=50
h=30
d=input("please enter your variable: ")
d=d.split(",")
print(d)
result=str(round(math.sqrt((2*c*int(d[0]))/h)))
for i in range(1,len(d)):
    result=result+","+str( round(math.sqrt((2*c*int(d[i]))/h))) 
print(result) 


please enter your variable: 1,0,2
['1', '0', '2']
2,0,3
